spring:
  application:
    name: user-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: "http://root:root@localhost:8761/eureka,\
                    http://root:root@localhost:8762/eureka"
    healthcheck:
      enabled: true

  instance:
    # 采用IP注册,优先于主机名，在点击实例跳转时有用
    prefer-ip-address: true
    # 定义实例ID格式
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    # 点击Instance ID进行跳转的地址
    status-page-url-path: /user/hello
    # 自定义元数据
    metadata-map:
      name: zhangsan

management:
  endpoints:
    web:
      exposure:
        include: "*"
