server:
  port: 9091

spring:
  application:
    name: spring-boot-admin

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: d:/tmp/admin.log
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAdress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAdress}:${server.port}
    metadata-map:
      user.name: admin
      user.password: admin

  client:
    service-url:
      defaultZone: "http://root:root@localhost:8761/eureka,\
                    http://root:root@localhost:8762/eureka"
